const monitorBinance = require('./exchanges/binance.js');
const monitorBithumb = require('./exchanges/bithumb.js');
const monitorBitfinex = require('./exchanges/bitfinex.js');
const monitorBittrex = require('./exchanges/bittrex.js');
const monitorPoloniex = require('./exchanges/poloniex.js');
const monitorBitstamp = require('./exchanges/bitstamp.js');
const monitorGdax = require('./exchanges/gdax.js');
const monitorHuobi = require('./exchanges/huobi.js');
const monitorCoinone = require('./exchanges/coinone.js');
const monitorHitbtc = require('./exchanges/hitbtc.js');

monitorBinance();
monitorBithumb();
monitorBitfinex();
monitorBittrex();
monitorPoloniex();
monitorBitstamp();
monitorGdax();
monitorHuobi();
monitorCoinone();
monitorHitbtc();